    # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
import figure
import setting


SPOTS_POS = setting.SPOTS_POS
SPOTS_NUMBER = len(SPOTS_POS)

class Hand(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.spot_pix_map = QtGui.QPixmap(":/hand/source/spot.png")

        self.hand_2 = QtWidgets.QLabel(self)
        self.hand_2.setGeometry(QtCore.QRect(0, 0, 350, 300))
        self.hand_2.setText("")
        self.hand_2.setPixmap(QtGui.QPixmap("./source/hand.png"))
        self.hand_2.setScaledContents(True)
        self.hand_2.setObjectName("hand_2")

        # self.spot_0 = QtWidgets.QLabel(self)
        # self.spot_0.setGeometry(QtCore.QRect(50, 160, 51, 41))
        # self.spot_0.setText("")
        # self.spot_0.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))    
        # self.spot_0.setScaledContents(True)
        # self.spot_0.setObjectName("spot_0")
        # self.spot_1 = QtWidgets.QLabel(self)
        # self.spot_1.setGeometry(QtCore.QRect(140, 30, 31, 31))
        # self.spot_1.setText("")
        # self.spot_1.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
        # self.spot_1.setScaledContents(True)
        # self.spot_1.setObjectName("spot_1")
        # self.spot_2 = QtWidgets.QLabel(self)
        # self.spot_2.setGeometry(QtCore.QRect(180, 20, 31, 31))
        # self.spot_2.setText("")
        # self.spot_2.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
        # self.spot_2.setScaledContents(True)
        # self.spot_2.setObjectName("spot_2")
        # self.spot_3 = QtWidgets.QLabel(self)
        # self.spot_3.setGeometry(QtCore.QRect(220, 40, 31, 31))
        # self.spot_3.setText("")
        # self.spot_3.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
        # self.spot_3.setScaledContents(True)
        # self.spot_3.setObjectName("spot_3")
        # self.spot_4 = QtWidgets.QLabel(self)
        # self.spot_4.setGeometry(QtCore.QRect(260, 60, 31, 31))
        # self.spot_4.setText("")
        # self.spot_4.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
        # self.spot_4.setScaledContents(True)
        # self.spot_4.setObjectName("spot_4")
        # self.spot_5 = QtWidgets.QLabel(self)
        # self.spot_5.setGeometry(QtCore.QRect(150, 150, 81, 71))
        # self.spot_5.setText("")
        # self.spot_5.setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
        # self.spot_5.setScaledContents(True)
        # self.spot_5.setObjectName("spot_5")

        self.spots = []
        for i in range(SPOTS_NUMBER):
            self.spots.append(QtWidgets.QLabel(self))
            self.spots[i].setGeometry(QtCore.QRect(SPOTS_POS[i][0], SPOTS_POS[i][1], SPOTS_POS[i][2], SPOTS_POS[i][3]))
            self.spots[i].setText("")
            self.spots[i].setPixmap(QtGui.QPixmap(":/hand/source/spot.png"))
            self.spots[i].setScaledContents(True)
            self.spots[i].setObjectName("spot_{}".format(i))
    # set the opacity of the spots to show the irritation of the parts in hand
    '''
    @parm
    ids: the indexes of spots
    values: the opacity of spots 
    '''

    def set_value(self,ids,values):
        if len(ids) > SPOTS_NUMBER:
            raise ValueError("the number os ids is {} which is out of range".format(len(ids)))
        if len(ids) != len(values):
            raise ValueError("the length of ids doesn't equal to the length of values")
        for i in ids:
            new_pix = QtGui.QPixmap(self.spots[i].pixmap().size())
            new_pix.fill(QtCore.Qt.transparent)
            painter = QtGui.QPainter(new_pix)
            print("value is {}".format(values[i]))
            painter.setOpacity(values[i])
            painter.drawPixmap(QtCore.QPoint(), self.spot_pix_map)
            painter.end()
            self.spots[i].setPixmap(new_pix)
        # if id == 5:
        #     self.spot_5.setWindowOpacity(value)
        #     pix_map = QtGui.QPixmap(":/hand/source/spot.png")
        #     new_pix = QtGui.QPixmap(self.spot_5.pixmap().size())
        #     new_pix.fill(QtCore.Qt.transparent)
        #     painter = QtGui.QPainter(new_pix)
        #     print("value is {}".format(value))
        #     painter.setOpacity(value * 0.01)
        #     painter.drawPixmap(QtCore.QPoint(), pix_map)
        #     painter.end()
        #     self.spot_5.setPixmap(new_pix)

