# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.finger_state_widget = QtWidgets.QWidget(self.centralwidget)
        self.finger_state_widget.setGeometry(QtCore.QRect(40, 340, 401, 189))
        self.finger_state_widget.setObjectName("finger_state_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.finger_state_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.finger_label_5 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_5.setObjectName("finger_label_5")
        self.gridLayout.addWidget(self.finger_label_5, 5, 0, 1, 1)
        self.finger_label = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label.setObjectName("finger_label")
        self.gridLayout.addWidget(self.finger_label, 1, 0, 1, 1)
        self.finger_label_4 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_4.setObjectName("finger_label_4")
        self.gridLayout.addWidget(self.finger_label_4, 4, 0, 1, 1)
        self.finger_label_3 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_3.setObjectName("finger_label_3")
        self.gridLayout.addWidget(self.finger_label_3, 3, 0, 1, 1)
        self.time_spinBox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.time_spinBox.setObjectName("time_spinBox")
        self.gridLayout.addWidget(self.time_spinBox, 1, 4, 1, 1)
        self.finger_label_7 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_7.setObjectName("finger_label_7")
        self.gridLayout.addWidget(self.finger_label_7, 0, 1, 1, 1)
        self.finger_3_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_3_spinbox.setObjectName("finger_3_spinbox")
        self.gridLayout.addWidget(self.finger_3_spinbox, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.finger_state_widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.finger_label_6 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_6.setObjectName("finger_label_6")
        self.gridLayout.addWidget(self.finger_label_6, 6, 0, 1, 1)
        self.finger_set_pushbutton = QtWidgets.QPushButton(self.finger_state_widget)
        self.finger_set_pushbutton.setObjectName("finger_set_pushbutton")
        self.gridLayout.addWidget(self.finger_set_pushbutton, 4, 4, 1, 1)
        self.finger_0_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_0_spinbox.setObjectName("finger_0_spinbox")
        self.gridLayout.addWidget(self.finger_0_spinbox, 1, 1, 1, 1)
        self.finger_4_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_4_spinbox.setObjectName("finger_4_spinbox")
        self.gridLayout.addWidget(self.finger_4_spinbox, 5, 1, 1, 1)
        self.finger_2_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_2_spinbox.setObjectName("finger_2_spinbox")
        self.gridLayout.addWidget(self.finger_2_spinbox, 3, 1, 1, 1)
        self.finger_5_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_5_spinbox.setObjectName("finger_5_spinbox")
        self.gridLayout.addWidget(self.finger_5_spinbox, 6, 1, 1, 1)
        self.finger_label_2 = QtWidgets.QLabel(self.finger_state_widget)
        self.finger_label_2.setObjectName("finger_label_2")
        self.gridLayout.addWidget(self.finger_label_2, 2, 0, 1, 1)
        self.finger_1_spinbox = QtWidgets.QSpinBox(self.finger_state_widget)
        self.finger_1_spinbox.setObjectName("finger_1_spinbox")
        self.gridLayout.addWidget(self.finger_1_spinbox, 2, 1, 1, 1)
        self.finger_0_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_0_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_0_horizontalSlider.setObjectName("finger_0_horizontalSlider")
        self.gridLayout.addWidget(self.finger_0_horizontalSlider, 1, 2, 1, 1)
        self.finger_1_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_1_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_1_horizontalSlider.setObjectName("finger_1_horizontalSlider")
        self.gridLayout.addWidget(self.finger_1_horizontalSlider, 2, 2, 1, 1)
        self.finger_2_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_2_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_2_horizontalSlider.setObjectName("finger_2_horizontalSlider")
        self.gridLayout.addWidget(self.finger_2_horizontalSlider, 3, 2, 1, 1)
        self.finger_3_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_3_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_3_horizontalSlider.setObjectName("finger_3_horizontalSlider")
        self.gridLayout.addWidget(self.finger_3_horizontalSlider, 4, 2, 1, 1)
        self.finger_4_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_4_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_4_horizontalSlider.setObjectName("finger_4_horizontalSlider")
        self.gridLayout.addWidget(self.finger_4_horizontalSlider, 5, 2, 1, 1)
        self.finger_5_horizontalSlider = QtWidgets.QSlider(self.finger_state_widget)
        self.finger_5_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.finger_5_horizontalSlider.setObjectName("finger_5_horizontalSlider")
        self.gridLayout.addWidget(self.finger_5_horizontalSlider, 6, 2, 1, 1)
        self.default_gesture_widget = QtWidgets.QWidget(self.centralwidget)
        self.default_gesture_widget.setGeometry(QtCore.QRect(630, 126, 99, 181))
        self.default_gesture_widget.setObjectName("default_gesture_widget")
        self.formLayout = QtWidgets.QFormLayout(self.default_gesture_widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.gesture_0_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_0_pushButton.setObjectName("gesture_0_pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gesture_0_pushButton)
        self.gesture_1_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_1_pushButton.setObjectName("gesture_1_pushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gesture_1_pushButton)
        self.gesture_2_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_2_pushButton.setObjectName("gesture_2_pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gesture_2_pushButton)
        self.gesture_3_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_3_pushButton.setObjectName("gesture_3_pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.gesture_3_pushButton)
        self.gesture_4_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_4_pushButton.setObjectName("gesture_4_pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gesture_4_pushButton)
        self.gesture_5_pushButton = QtWidgets.QPushButton(self.default_gesture_widget)
        self.gesture_5_pushButton.setObjectName("gesture_5_pushButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gesture_5_pushButton)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 60, 301, 241))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(110, 10, 71, 16))
        self.label.setObjectName("label")
        self.com_widget = QtWidgets.QWidget(self.centralwidget)
        self.com_widget.setGeometry(QtCore.QRect(520, 380, 201, 94))
        self.com_widget.setObjectName("com_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.com_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.com_close_pushButton = QtWidgets.QPushButton(self.com_widget)
        self.com_close_pushButton.setObjectName("com_close_pushButton")
        self.gridLayout_2.addWidget(self.com_close_pushButton, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.com_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.com_comboBox = QtWidgets.QComboBox(self.com_widget)
        self.com_comboBox.setObjectName("com_comboBox")
        self.gridLayout_2.addWidget(self.com_comboBox, 0, 1, 1, 1)
        self.com_connect_pushButton = QtWidgets.QPushButton(self.com_widget)
        self.com_connect_pushButton.setObjectName("com_connect_pushButton")
        self.gridLayout_2.addWidget(self.com_connect_pushButton, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.com_widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.bps_comboBox = QtWidgets.QComboBox(self.com_widget)
        self.bps_comboBox.setObjectName("bps_comboBox")
        self.gridLayout_2.addWidget(self.bps_comboBox, 3, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(540, 40, 120, 80))
        self.widget_2.setObjectName("widget_2")
        self.slider_spin_0 = Ui_SliderAndSpin(self.centralwidget)
        self.slider_spin_0.setGeometry(QtCore.QRect(400, 170, 120, 80))
        self.slider_spin_0.setObjectName("slider_spin_0")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.finger_label_5.setText(_translate("MainWindow", "无名指"))
        self.finger_label.setText(_translate("MainWindow", "手掌"))
        self.finger_label_4.setText(_translate("MainWindow", "中指"))
        self.finger_label_3.setText(_translate("MainWindow", "食指"))
        self.finger_label_7.setText(_translate("MainWindow", "单次手势调整"))
        self.label_2.setText(_translate("MainWindow", "时间"))
        self.finger_label_6.setText(_translate("MainWindow", "小指"))
        self.finger_set_pushbutton.setText(_translate("MainWindow", "设置"))
        self.finger_label_2.setText(_translate("MainWindow", "拇指"))
        self.gesture_0_pushButton.setText(_translate("MainWindow", "手势一"))
        self.gesture_1_pushButton.setText(_translate("MainWindow", "手势二"))
        self.gesture_2_pushButton.setText(_translate("MainWindow", "手势三"))
        self.gesture_3_pushButton.setText(_translate("MainWindow", "手势四"))
        self.gesture_4_pushButton.setText(_translate("MainWindow", "手势五"))
        self.gesture_5_pushButton.setText(_translate("MainWindow", "手势六"))
        self.label.setText(_translate("MainWindow", "手势示意图"))
        self.com_close_pushButton.setText(_translate("MainWindow", "关闭串口"))
        self.label_3.setText(_translate("MainWindow", "选择串口"))
        self.com_connect_pushButton.setText(_translate("MainWindow", "打开串口"))
        self.label_4.setText(_translate("MainWindow", "波特率"))

from sliderandspin import Ui_SliderAndSpin
