# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SliderAndSpin(object):
    def setupUi(self, SliderAndSpin):
        SliderAndSpin.setObjectName("SliderAndSpin")
        SliderAndSpin.resize(649, 91)
        SliderAndSpin.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(SliderAndSpin)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SliderAndSpin)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(SliderAndSpin)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 20))
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.horizontalSlider = QtWidgets.QSlider(SliderAndSpin)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(200, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)

        self.retranslateUi(SliderAndSpin)
        QtCore.QMetaObject.connectSlotsByName(SliderAndSpin)

    def retranslateUi(self, SliderAndSpin):
        _translate = QtCore.QCoreApplication.translate
        SliderAndSpin.setWindowTitle(_translate("SliderAndSpin", "Form"))
        self.label.setText(_translate("SliderAndSpin", "TextLabel"))
